config/routes.rb
RailsLooper::Application.routes.draw do
  resources :loops

end

app/models/loop.rb
require 'uri'
class Loop < ActiveRecord::Base
  
  attr_accessible :url
  
  def self.this(url)
    uri = URI(url)
    if !uri.query.nil?
      code = uri.query
      code['v='] = '' 
    else
      code = uri.path
      code['/'] = ''
    end
    code = code.strip
    looper = '<iframe width="640" height="360" src="http://www.youtube.com/embed/'+code+'?autoplay=1&version=3&loop=1&playlist='+code+'" frameborder="0" allowfullscreen></iframe>'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/loops_controller.rb
class LoopsController < ApplicationController
  # GET /loops
  # GET /loops.json
  def index
    @loops = Loop.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @loops }
    end
  end

  # GET /loops/1
  # GET /loops/1.json
  def show
    @loop = Loop.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @loop }
    end
  end

  # GET /loops/new
  # GET /loops/new.json
  def new
    @loop = Loop.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @loop }
    end
  end

  # GET /loops/1/edit
  def edit
    @loop = Loop.find(params[:id])
  end

  # POST /loops
  # POST /loops.json
  def create
    @loop = Loop.new(params[:loop])
    
    @loop.embedded = Loop.this @loop.url
    
    respond_to do |format|
      if @loop.save
        format.html { redirect_to @loop, notice: 'Loop was successfully created.' }
        format.json { render json: @loop, status: :created, location: @loop }
      else
        format.html { render action: "new" }
        format.json { render json: @loop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /loops/1
  # PUT /loops/1.json
  def update
    @loop = Loop.find(params[:id])

    respond_to do |format|
      if @loop.update_attributes(params[:loop])
        format.html { redirect_to @loop, notice: 'Loop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @loop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loops/1
  # DELETE /loops/1.json
  def destroy
    @loop = Loop.find(params[:id])
    @loop.destroy

    respond_to do |format|
      format.html { redirect_to loops_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/loops_helper.rb
module LoopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsLooper</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/loops/_form.html.haml
= form_for @loop do |f|
  - if @loop.errors.any?
    #error_explanation
      %h2= "#{pluralize(@loop.errors.count, "error")} prohibited this loop from being saved:"
      %ul
        - @loop.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :url
    = f.text_field :url
  .actions
    = f.submit 'Save'

app/views/loops/edit.html.haml
%h1 Editing loop

= render 'form'

= link_to 'Show', @loop
\|
= link_to 'Back', loops_path

app/views/loops/index.html.haml
%h1 Listing loops

%table
  %tr
    %th Url
    %th
    %th
    %th

  - @loops.each do |loop|
    %tr
      %td= loop.url
      %td= link_to 'Show', loop
      %td= link_to 'Edit', edit_loop_path(loop)
      %td= link_to 'Destroy', loop, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br


= link_to 'New Loop', new_loop_path

app/views/loops/new.html.haml
%h1 New loop

= render 'form'

= link_to 'Back', loops_path

app/views/loops/show.html.haml
%p#notice= notice

%p
  %b Url:
  %p= @loop.url
  %p= @loop.embedded

= link_to 'Edit', edit_loop_path(@loop)
\|
= link_to 'Back', loops_path